version: "3.8"

services:
  postgres:
    image: postgres:12-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5732:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: user_management_app
    ports:
      - "8000:8000" # REST
      - "50051:50051" # gRPC
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/usr/src/app-src

volumes:
  postgres_data:
