# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "user.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\x12\x04user"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t"\x14\n\x12HealthCheckRequest"B\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05".\n\x0b\x41uthRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"8\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t"0\n\x0eHealthResponse\x12\x0e\n\x06health\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xe3\x01\n\x0bUserService\x12\x31\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\n.user.User\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.User\x12\x35\n\x0c\x41uthenticate\x12\x11.user.AuthRequest\x1a\x12.user.AuthResponse\x12=\n\x0bHealthCheck\x12\x18.user.HealthCheckRequest\x1a\x14.user.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USER"]._serialized_start = 20
    _globals["_USER"]._serialized_end = 67
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 69
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 89
    _globals["_CREATEUSERREQUEST"]._serialized_start = 91
    _globals["_CREATEUSERREQUEST"]._serialized_end = 157
    _globals["_GETUSERREQUEST"]._serialized_start = 159
    _globals["_GETUSERREQUEST"]._serialized_end = 187
    _globals["_AUTHREQUEST"]._serialized_start = 189
    _globals["_AUTHREQUEST"]._serialized_end = 235
    _globals["_AUTHRESPONSE"]._serialized_start = 237
    _globals["_AUTHRESPONSE"]._serialized_end = 293
    _globals["_HEALTHRESPONSE"]._serialized_start = 295
    _globals["_HEALTHRESPONSE"]._serialized_end = 343
    _globals["_USERSERVICE"]._serialized_start = 346
    _globals["_USERSERVICE"]._serialized_end = 573
# @@protoc_insertion_point(module_scope)
